filegroup(
    name = "ide",
    srcs = [
        "Bazel.props",
        "Bazel.targets",
        "Directory.Build.props",
        "Directory.Build.targets",
        "Directory.Solution.props",
        "Directory.Solution.targets",
    ],
    visibility = ["//visibility:public"],
)
