load("//dotnet:defs.bzl", "dotnet_library")

package(default_visibility = ["//visibility:public"])

dotnet_library(
    name = "runfiles",
    srcs = [
        "BazelEnvironment.cs",
        "Check.cs",
        "Runfiles.cs",
    ],
    target_framework = "netstandard2.1",
)
