load("//dotnet:defs.bzl", "dotnet_library")

dotnet_library(
    name = "runfiles",
    srcs = [
        "BazelEnvironment.cs",
        "Check.cs",
        "Label.cs",
        "LabelRunfiles.cs",
        "Runfiles.cs",
    ],
    sdk = "Microsoft.NET.Sdk",
    target_framework = "netstandard2.1",
    visibility = ["//visibility:public"],
)
