filegroup(
    name = "bootstrapper_srcs",
    srcs = [
        "BazelEnvironment.cs",
        "Label.cs",
        "Program.cs",
        "QueryParser.cs",
    ],
    visibility = ["//visibility:public"],
)
