# gazelle:exclude *.proj

exports_files([
    "NuGet.tpl.config",
    "project.tpl.proj",
    "project.tpl.new.proj",
    "AlternateCommonProps.props",
    "Directory.Bazel.props",
    "Directory.Bazel.targets",
])
