load(":toolchains.bzl", "declare_constraints")

package(default_visibility = ["//visibility:public"])

toolchain_type(
    name = "toolchain",
    visibility = ["//visibility:public"],
)

declare_constraints()
