#load("//dotnet:defs.bzl", "dotnet_test")
#load("//dotnet:defs.bzl", "")
#
#dotnet_test(
#    name = "HelloTest_test",
#    srcs = ["HelloTest.cs"],
#    target_framework = "netcoreapp3.1",
#    deps = [
#        "@nuget//xunit",
#        "@nuget//xunit.runner.visualstudio",
#    ],
#)
#
#binary_test(
#    name = "HelloTest_test_test",
#    expected_files = {
#        "netcoreapp3.1": [
#            "HelloTest_test.dll",
#            "xunit.assert.dll",
#        ],
#    },
#    expected_output = None,
#    target = "HelloTest_test",
#)
