# Simply a sanity test so I know that bazel is running and processing the workspace correctly

load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "sanity",
    srcs = ["hello.go"],
)
