load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "executable_fixture",
    srcs = ["executable_fixture.py"],
    visibility = ["//visibility:public"],
    deps = [
        "@rules_python//python/runfiles",
    ],
)
