load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "repositories",
    srcs = ["repositories.bzl"],
    visibility = ["//dotnet:__subpackages__"],
    deps = [],
)

bzl_library(
    name = "sdk",
    srcs = ["sdk.bzl"],
    visibility = ["//dotnet:__subpackages__"],
    deps = [],
)