load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "files",
    srcs = ["files.go"],
    importpath = "github.com/samhowes/rules_msbuild/tests/tools/files",
    visibility = ["//visibility:public"],
    deps = ["@io_bazel_rules_go//go/tools/bazel:go_default_library"],
)
