# this will be appended to the templated WORKSPACE fragment in Bzl

load("@rules_msbuild//dotnet:defs.bzl", "nuget_fetch")
load("@rules_msbuild//deps:nuget.bzl", "FRAMEWORKS", "PACKAGES")
load("@bazel_skylib//lib:dicts.bzl", "dicts")

nuget_fetch(
    name = "nuget",
    packages = dicts.add(
        {
            "CommandLineParser:2.8.0": ["net5.0"],
        },
        PACKAGES,
    ),
    target_frameworks = ["net5.0"] + FRAMEWORKS,
    use_host = True,
)
