load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

package(default_visibility = ["//dotnet:__subpackages__"])

bzl_library(
    name = "binary",
    srcs = ["binary.bzl"],
)

bzl_library(
    name = "compile",
    srcs = ["compile.bzl"],
)


bzl_library(
    name = "pack",
    srcs = ["pack.bzl"],
)

bzl_library(
    name = "stdlib",
    srcs = ["stdlib.bzl"],
)
