load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

package(default_visibility = ["//dotnet:__subpackages__"])

bzl_library(
    name = "assembly",
    srcs = ["binary.bzl"],
)

bzl_library(
    name = "common",
    srcs = ["common.bzl"],
)
